# Generated by Django 5.2.4 on 2025-07-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
